/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddressRouteImport } from './routes/address'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SavedAddressRouteImport } from './routes/saved-address'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as VouchersRouteImport } from './routes/vouchers'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStockRouteImport } from './routes/admin.stock'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as MenuItemIdRouteImport } from './routes/menu.$itemId'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerAuditRouteImport } from './routes/owner.audit'
import { Route as OwnerFinanceRouteImport } from './routes/owner.finance'
import { Route as OwnerMenuRouteImport } from './routes/owner.menu'
import { Route as OwnerOutletsRouteImport } from './routes/owner.outlets'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as OwnerShippingRouteImport } from './routes/owner.shipping'
import { Route as OwnerStaffRouteImport } from './routes/owner.staff'
import { Route as OwnerVouchersRouteImport } from './routes/owner.vouchers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressRoute = AddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedAddressRoute = SavedAddressRouteImport.update({
  id: '/saved-address',
  path: '/saved-address',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const VouchersRoute = VouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminRoute,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuItemIdRoute = MenuItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => MenuRoute,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAuditRoute = OwnerAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerFinanceRoute = OwnerFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMenuRoute = OwnerMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOutletsRoute = OwnerOutletsRouteImport.update({
  id: '/outlets',
  path: '/outlets',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerShippingRoute = OwnerShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerStaffRoute = OwnerStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerVouchersRoute = OwnerVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => OwnerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRouteWithChildren
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/saved-address': typeof SavedAddressRoute
  '/tracking': typeof TrackingRoute
  '/vouchers': typeof VouchersRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock': typeof AdminStockRoute
  '/menu/$itemId': typeof MenuItemIdRoute
  '/owner/audit': typeof OwnerAuditRoute
  '/owner/finance': typeof OwnerFinanceRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/outlets': typeof OwnerOutletsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/shipping': typeof OwnerShippingRoute
  '/owner/staff': typeof OwnerStaffRoute
  '/owner/vouchers': typeof OwnerVouchersRoute
  '/admin/': typeof AdminIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/saved-address': typeof SavedAddressRoute
  '/tracking': typeof TrackingRoute
  '/vouchers': typeof VouchersRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock': typeof AdminStockRoute
  '/menu/$itemId': typeof MenuItemIdRoute
  '/owner/audit': typeof OwnerAuditRoute
  '/owner/finance': typeof OwnerFinanceRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/outlets': typeof OwnerOutletsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/shipping': typeof OwnerShippingRoute
  '/owner/staff': typeof OwnerStaffRoute
  '/owner/vouchers': typeof OwnerVouchersRoute
  '/admin': typeof AdminIndexRoute
  '/menu': typeof MenuIndexRoute
  '/owner': typeof OwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRouteWithChildren
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/saved-address': typeof SavedAddressRoute
  '/tracking': typeof TrackingRoute
  '/vouchers': typeof VouchersRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock': typeof AdminStockRoute
  '/menu/$itemId': typeof MenuItemIdRoute
  '/owner/audit': typeof OwnerAuditRoute
  '/owner/finance': typeof OwnerFinanceRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/outlets': typeof OwnerOutletsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/shipping': typeof OwnerShippingRoute
  '/owner/staff': typeof OwnerStaffRoute
  '/owner/vouchers': typeof OwnerVouchersRoute
  '/admin/': typeof AdminIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/address'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/menu'
    | '/order-success'
    | '/orders'
    | '/owner'
    | '/profile'
    | '/register'
    | '/saved-address'
    | '/tracking'
    | '/vouchers'
    | '/admin/customers'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/stock'
    | '/menu/$itemId'
    | '/owner/audit'
    | '/owner/finance'
    | '/owner/menu'
    | '/owner/outlets'
    | '/owner/settings'
    | '/owner/shipping'
    | '/owner/staff'
    | '/owner/vouchers'
    | '/admin/'
    | '/menu/'
    | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/address'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/order-success'
    | '/orders'
    | '/profile'
    | '/register'
    | '/saved-address'
    | '/tracking'
    | '/vouchers'
    | '/admin/customers'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/stock'
    | '/menu/$itemId'
    | '/owner/audit'
    | '/owner/finance'
    | '/owner/menu'
    | '/owner/outlets'
    | '/owner/settings'
    | '/owner/shipping'
    | '/owner/staff'
    | '/owner/vouchers'
    | '/admin'
    | '/menu'
    | '/owner'
  id:
    | '__root__'
    | '/'
    | '/address'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/menu'
    | '/order-success'
    | '/orders'
    | '/owner'
    | '/profile'
    | '/register'
    | '/saved-address'
    | '/tracking'
    | '/vouchers'
    | '/admin/customers'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/stock'
    | '/menu/$itemId'
    | '/owner/audit'
    | '/owner/finance'
    | '/owner/menu'
    | '/owner/outlets'
    | '/owner/settings'
    | '/owner/shipping'
    | '/owner/staff'
    | '/owner/vouchers'
    | '/admin/'
    | '/menu/'
    | '/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressRoute: typeof AddressRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRouteWithChildren
  OrderSuccessRoute: typeof OrderSuccessRoute
  OrdersRoute: typeof OrdersRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SavedAddressRoute: typeof SavedAddressRoute
  TrackingRoute: typeof TrackingRoute
  VouchersRoute: typeof VouchersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address': {
      id: '/address'
      path: '/address'
      fullPath: '/address'
      preLoaderRoute: typeof AddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-address': {
      id: '/saved-address'
      path: '/saved-address'
      fullPath: '/saved-address'
      preLoaderRoute: typeof SavedAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vouchers': {
      id: '/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof VouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/menu/': {
      id: '/menu/'
      path: '/'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/$itemId': {
      id: '/menu/$itemId'
      path: '/$itemId'
      fullPath: '/menu/$itemId'
      preLoaderRoute: typeof MenuItemIdRouteImport
      parentRoute: typeof MenuRoute
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/audit': {
      id: '/owner/audit'
      path: '/audit'
      fullPath: '/owner/audit'
      preLoaderRoute: typeof OwnerAuditRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/finance': {
      id: '/owner/finance'
      path: '/finance'
      fullPath: '/owner/finance'
      preLoaderRoute: typeof OwnerFinanceRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/menu': {
      id: '/owner/menu'
      path: '/menu'
      fullPath: '/owner/menu'
      preLoaderRoute: typeof OwnerMenuRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/outlets': {
      id: '/owner/outlets'
      path: '/outlets'
      fullPath: '/owner/outlets'
      preLoaderRoute: typeof OwnerOutletsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/shipping': {
      id: '/owner/shipping'
      path: '/shipping'
      fullPath: '/owner/shipping'
      preLoaderRoute: typeof OwnerShippingRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/staff': {
      id: '/owner/staff'
      path: '/staff'
      fullPath: '/owner/staff'
      preLoaderRoute: typeof OwnerStaffRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/vouchers': {
      id: '/owner/vouchers'
      path: '/vouchers'
      fullPath: '/owner/vouchers'
      preLoaderRoute: typeof OwnerVouchersRouteImport
      parentRoute: typeof OwnerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStockRoute: AdminStockRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MenuRouteChildren {
  MenuItemIdRoute: typeof MenuItemIdRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuItemIdRoute: MenuItemIdRoute,
  MenuIndexRoute: MenuIndexRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

interface OwnerRouteChildren {
  OwnerAuditRoute: typeof OwnerAuditRoute
  OwnerFinanceRoute: typeof OwnerFinanceRoute
  OwnerMenuRoute: typeof OwnerMenuRoute
  OwnerOutletsRoute: typeof OwnerOutletsRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerShippingRoute: typeof OwnerShippingRoute
  OwnerStaffRoute: typeof OwnerStaffRoute
  OwnerVouchersRoute: typeof OwnerVouchersRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAuditRoute: OwnerAuditRoute,
  OwnerFinanceRoute: OwnerFinanceRoute,
  OwnerMenuRoute: OwnerMenuRoute,
  OwnerOutletsRoute: OwnerOutletsRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerShippingRoute: OwnerShippingRoute,
  OwnerStaffRoute: OwnerStaffRoute,
  OwnerVouchersRoute: OwnerVouchersRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressRoute: AddressRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRouteWithChildren,
  OrderSuccessRoute: OrderSuccessRoute,
  OrdersRoute: OrdersRoute,
  OwnerRoute: OwnerRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SavedAddressRoute: SavedAddressRoute,
  TrackingRoute: TrackingRoute,
  VouchersRoute: VouchersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
